fastlane_version "1.105.1"

default_platform :ios

platform :ios do
    #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'MeetXSweatProd’, export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['m.boumansour1@hotmail.fr', 'm.boumansour1@gmail.com', 'aitbouzid.linda@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '62977dc8c8f12b0dde348863eb757d3007e2c01a',
             build_secret: '61af0811c6d6d49ebc29aa3bd09db050f141c44afb916a7337abd8c2e8a2235c',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
